OnChainTest contract
yieldprotocol/yield-utils-v2 pull request #34
Opened 2022-04-07 11:11 UTC by iamsahu

2022-04-07 11:15 UTC, alcueca requested changes
I feel bad about asking for tests on something this simple, but we are going to secure multimillion governance changes with this contract. Please?

Otherwise, all good. Excited about using this.

2022-04-07 12:30 UTC, alcueca requested changes
You forgot to check it returns true ;)

2022-04-08 07:34 UTC, iamsahu commented on test/007_onchaintest.ts
> +			await onChainTest.twoCallsEquator(
The function doesn't have an explicit return true so running expect to be true would fail.

2022-04-08 13:59 UTC, alcueca commented on test/007_onchaintest.ts
> +			await onChainTest.twoCallsEquator(
Ah, I see, it reverts if it's not true.

2022-04-08 14:02 UTC, alcueca approved these changes
:ship:

2022-04-08 14:03 UTC, merged