feat: add Pausable.sol
yieldprotocol/yield-utils-v2 pull request #47
Opened 2022-07-31 05:27 UTC by calnix

2022-08-02 15:10 UTC, alcueca requested changes
The fixes required are pretty minor.

2022-08-02 15:10 UTC, alcueca commented on foundry/src/Pausable.sol
> +contract Pausable is AccessControl {
It will be funny to see how the inheritance tree works if a Wand inherits from both Pausable and AccessControl

2022-08-03 01:56 UTC, calnix commented on foundry/src/Pausable.sol
> +    require(paused == false, "Pausable: paused");
Just wanted to confirm, do we really want to switch to using custom errors - when we adhere to require statements everywhere else?

2022-08-05 09:34 UTC, alcueca commented on foundry/src/Pausable.sol
> +    require(paused == false, "Pausable: paused");
Yeah, we are switching to errors every time we refactor something.

2022-08-08 11:32 UTC, alcueca approved these changes
Minor thing, please correct the naming and then merge.

2022-08-08 11:32 UTC, alcueca commented on foundry/src/Pausable.sol
> +  error requirePaused(address msgSender, bool pausedState);
Errors are UpperCamelCase

2022-08-08 11:40 UTC, merged